-- MySQL Script generated by MySQL Workbench
-- Wed Feb  6 13:16:20 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema TEI_XML_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `TEI_XML_db` ;

-- -----------------------------------------------------
-- Schema TEI_XML_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `TEI_XML_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci ;
USE `TEI_XML_db` ;

-- -----------------------------------------------------
-- Table `TEI_XML_db`.`Bibliography`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TEI_XML_db`.`Bibliography` ;

CREATE TABLE IF NOT EXISTS `TEI_XML_db`.`Bibliography` (
  `bibliographyId` INT(11) NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(50) NULL DEFAULT NULL,
  `bibl` VARCHAR(50) NULL DEFAULT NULL,
  `Reference_referenceId` INT(11) NOT NULL,
  `Reference_Entry_entryId` INT(11) NOT NULL,
  PRIMARY KEY (`bibliographyId`, `Reference_referenceId`, `Reference_Entry_entryId`),
  INDEX `fk_Bibliography_Reference1_idx` (`Reference_referenceId` ASC, `Reference_Entry_entryId` ASC) VISIBLE,
  CONSTRAINT `fk_Bibliography_Reference1`
    FOREIGN KEY (`Reference_referenceId` , `Reference_Entry_entryId`)
    REFERENCES `TEI_XML_db`.`Reference` (`referenceId` , `Entry_entryId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_general_ci;


-- -----------------------------------------------------
-- Table `TEI_XML_db`.`Citation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TEI_XML_db`.`Citation` ;

CREATE TABLE IF NOT EXISTS `TEI_XML_db`.`Citation` (
  `citationId` INT(11) NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(50) NULL DEFAULT NULL,
  `n` INT(11) NULL DEFAULT NULL,
  `Entry_entryId` INT(11) NOT NULL,
  PRIMARY KEY (`citationId`, `Entry_entryId`),
  INDEX `fk_Citation_Entry1_idx` (`Entry_entryId` ASC) VISIBLE,
  CONSTRAINT `fk_Citation_Entry1`
    FOREIGN KEY (`Entry_entryId`)
    REFERENCES `TEI_XML_db`.`entry` (`entryId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_general_ci;


-- -----------------------------------------------------
-- Table `TEI_XML_db`.`Definition`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TEI_XML_db`.`Definition` ;

CREATE TABLE IF NOT EXISTS `TEI_XML_db`.`Definition` (
  `definitionId` INT(11) NOT NULL AUTO_INCREMENT,
  `lang` VARCHAR(50) NULL DEFAULT NULL,
  `corresp` VARCHAR(50) NULL DEFAULT NULL,
  `definition` VARCHAR(300) NULL DEFAULT NULL,
  `Entry_entryId` INT(11) NOT NULL,
  PRIMARY KEY (`definitionId`, `Entry_entryId`),
  INDEX `fk_Definition_Entry1_idx` (`Entry_entryId` ASC) VISIBLE,
  CONSTRAINT `fk_Definition_Entry1`
    FOREIGN KEY (`Entry_entryId`)
    REFERENCES `TEI_XML_db`.`entry` (`entryId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_general_ci;


-- -----------------------------------------------------
-- Table `TEI_XML_db`.`Entry`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TEI_XML_db`.`Entry` ;

CREATE TABLE IF NOT EXISTS `TEI_XML_db`.`Entry` (
  `entryId` INT(11) NOT NULL AUTO_INCREMENT,
  `id` VARCHAR(200) NOT NULL,
  `lang` CHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`entryId`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_general_ci;


-- -----------------------------------------------------
-- Table `TEI_XML_db`.`Form`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TEI_XML_db`.`Form` ;

CREATE TABLE IF NOT EXISTS `TEI_XML_db`.`Form` (
  `formId` INT(11) NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(50) NULL DEFAULT NULL,
  `n` INT(11) NULL DEFAULT NULL,
  `Entry_entryId` INT(11) NOT NULL,
  PRIMARY KEY (`formId`, `Entry_entryId`),
  INDEX `fk_Form_Entry1_idx` (`Entry_entryId` ASC) VISIBLE,
  CONSTRAINT `fk_Form_Entry1`
    FOREIGN KEY (`Entry_entryId`)
    REFERENCES `TEI_XML_db`.`entry` (`entryId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_general_ci;


-- -----------------------------------------------------
-- Table `TEI_XML_db`.`GrammarGroup`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TEI_XML_db`.`GrammarGroup` ;

CREATE TABLE IF NOT EXISTS `TEI_XML_db`.`GrammarGroup` (
  `grammarGroupId` INT(11) NOT NULL AUTO_INCREMENT,
  `gram` VARCHAR(50) NULL DEFAULT NULL,
  `pos` VARCHAR(50) NULL DEFAULT NULL,
  `Entry_entryId` INT(11) NOT NULL,
  PRIMARY KEY (`grammarGroupId`, `Entry_entryId`),
  INDEX `fk_GrammarGroup_Entry1_idx` (`Entry_entryId` ASC) VISIBLE,
  CONSTRAINT `fk_GrammarGroup_Entry1`
    FOREIGN KEY (`Entry_entryId`)
    REFERENCES `TEI_XML_db`.`entry` (`entryId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_general_ci;


-- -----------------------------------------------------
-- Table `TEI_XML_db`.`Note`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TEI_XML_db`.`Note` ;

CREATE TABLE IF NOT EXISTS `TEI_XML_db`.`Note` (
  `noteId` INT(11) NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(50) NULL DEFAULT NULL,
  `resp` VARCHAR(200) NULL DEFAULT NULL,
  `corresp` VARCHAR(50) NULL DEFAULT NULL,
  `note` VARCHAR(300) NULL DEFAULT NULL,
  `entryid` INT(11) NULL DEFAULT NULL,
  `Entry_entryId` INT(11) NOT NULL,
  PRIMARY KEY (`noteId`, `Entry_entryId`),
  INDEX `Entry_idx` (`entryid` ASC) VISIBLE,
  INDEX `fk_Note_Entry1_idx` (`Entry_entryId` ASC) VISIBLE,
  CONSTRAINT `NoteEntry`
    FOREIGN KEY (`entryid`)
    REFERENCES `TEI_XML_db`.`entry` (`entryId`),
  CONSTRAINT `fk_Note_Entry1`
    FOREIGN KEY (`Entry_entryId`)
    REFERENCES `TEI_XML_db`.`entry` (`entryId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_general_ci;


-- -----------------------------------------------------
-- Table `TEI_XML_db`.`orth`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TEI_XML_db`.`Orth` ;

CREATE TABLE IF NOT EXISTS `TEI_XML_db`.`Orth` (
  `orthId` INT(11) NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(50) NULL DEFAULT NULL,
  `orth` VARCHAR(300) NULL DEFAULT NULL,
  `Entry_entryId` INT(11) NOT NULL,
  PRIMARY KEY (`orthId`, `Entry_entryId`),
  INDEX `fk_orth_Entry1_idx` (`Entry_entryId` ASC) VISIBLE,
  CONSTRAINT `fk_orth_Entry1`
    FOREIGN KEY (`Entry_entryId`)
    REFERENCES `TEI_XML_db`.`entry` (`entryId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_general_ci;


-- -----------------------------------------------------
-- Table `TEI_XML_db`.`Place`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TEI_XML_db`.`Place` ;

CREATE TABLE IF NOT EXISTS `TEI_XML_db`.`Place` (
  `placeId` INT(11) NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(50) NULL DEFAULT NULL,
  `name` VARCHAR(50) NULL DEFAULT NULL,
  `id` VARCHAR(45) NULL DEFAULT NULL,
  `Entry_entryId` INT(11) NOT NULL,
  PRIMARY KEY (`placeId`, `Entry_entryId`),
  INDEX `fk_Place_Entry1_idx` (`Entry_entryId` ASC) VISIBLE,
  CONSTRAINT `fk_Place_Entry1`
    FOREIGN KEY (`Entry_entryId`)
    REFERENCES `TEI_XML_db`.`entry` (`entryId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_general_ci;


-- -----------------------------------------------------
-- Table `TEI_XML_db`.`pronunciation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TEI_XML_db`.`Pronunciation` ;

CREATE TABLE IF NOT EXISTS `TEI_XML_db`.`pronunciation` (
  `pronunciationId` INT(11) NOT NULL AUTO_INCREMENT,
  `notation` VARCHAR(50) NULL DEFAULT NULL,
  `resp` VARCHAR(50) NULL DEFAULT NULL,
  `change` VARCHAR(50) NULL DEFAULT NULL,
  `pron` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`pronunciationId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_general_ci;


-- -----------------------------------------------------
-- Table `TEI_XML_db`.`Quote`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TEI_XML_db`.`Quote` ;

CREATE TABLE IF NOT EXISTS `TEI_XML_db`.`Quote` (
  `quoteId` INT(11) NOT NULL,
  `resp` VARCHAR(50) NULL DEFAULT NULL,
  `change` VARCHAR(50) NULL DEFAULT NULL,
  `quote` VARCHAR(50) NULL DEFAULT NULL,
  `Citation_citationId` INT(11) NOT NULL,
  `Citation_Entry_entryId` INT(11) NOT NULL,
  PRIMARY KEY (`quoteId`, `Citation_citationId`, `Citation_Entry_entryId`),
  INDEX `fk_Quote_Citation1_idx` (`Citation_citationId` ASC, `Citation_Entry_entryId` ASC) VISIBLE,
  CONSTRAINT `fk_Quote_Citation1`
    FOREIGN KEY (`Citation_citationId` , `Citation_Entry_entryId`)
    REFERENCES `TEI_XML_db`.`Citation` (`citationId` , `Entry_entryId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_general_ci;


-- -----------------------------------------------------
-- Table `TEI_XML_db`.`Reference`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TEI_XML_db`.`Reference` ;

CREATE TABLE IF NOT EXISTS `TEI_XML_db`.`Reference` (
  `referenceId` INT(11) NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(50) NULL DEFAULT NULL,
  `ref` VARCHAR(300) NULL DEFAULT NULL,
  `date` VARCHAR(20) NULL DEFAULT NULL COMMENT 'This field needs further treatment as there are dates of various formats in the tei/xml file.',
  `Entry_entryId` INT(11) NOT NULL,
  PRIMARY KEY (`referenceId`, `Entry_entryId`),
  INDEX `fk_Reference_Entry1_idx` (`Entry_entryId` ASC) VISIBLE,
  CONSTRAINT `fk_Reference_Entry1`
    FOREIGN KEY (`Entry_entryId`)
    REFERENCES `TEI_XML_db`.`entry` (`entryId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_general_ci;


-- -----------------------------------------------------
-- Table `TEI_XML_db`.`Sense`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TEI_XML_db`.`Sense` ;

CREATE TABLE IF NOT EXISTS `TEI_XML_db`.`Sense` (
  `senseId` INT(11) NOT NULL AUTO_INCREMENT,
  `corresp` VARCHAR(50) NULL DEFAULT NULL,
  `Entry_entryId` INT(11) NOT NULL,
  PRIMARY KEY (`senseId`, `Entry_entryId`),
  INDEX `fk_Sense_Entry1_idx` (`Entry_entryId` ASC) VISIBLE,
  CONSTRAINT `fk_Sense_Entry1`
    FOREIGN KEY (`Entry_entryId`)
    REFERENCES `TEI_XML_db`.`entry` (`entryId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_general_ci;


-- -----------------------------------------------------
-- Table `TEI_XML_db`.`usage`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TEI_XML_db`.`Usage` ;

CREATE TABLE IF NOT EXISTS `TEI_XML_db`.`usage` (
  `usageId` INT(11) NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(50) NULL DEFAULT NULL,
  `Entry_entryId` INT(11) NOT NULL,
  PRIMARY KEY (`usageId`, `Entry_entryId`),
  INDEX `fk_usage_Entry1_idx` (`Entry_entryId` ASC) VISIBLE,
  CONSTRAINT `fk_usage_Entry1`
    FOREIGN KEY (`Entry_entryId`)
    REFERENCES `TEI_XML_db`.`entry` (`entryId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_general_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
